### ISSUE TITLE
OSX build fails: "/old_openssl_shim.c:39:12: error: returning 'void' from a function with incompatible result type 'int'"

### ISSUE THREAD

**Issue by Adenilson** [sfackler/rust-openssl#162]
Doing some digging revealed that Xcode headers* have a different function return type than openssl installed by brew**.

A dirty fix is just to change the function return types in old_openssl_shim.c (i.e. https://gist.github.com/Adenilson/a60a1a2a5415e7929e6b) but for sure it will case problems if there is a failure.

Inspecting the stdout flags used by cargo reveals that the CFLAGS variable is empty***, but running 'pkg-config --cflags openssl' returns the right include dirs (e.g. -I/opt/local/include).

As a test, I was able to compile the file by hand running:
gcc -c -I/opt/local/include  -ffunction-sections -fdata-sections -m64 -fPIC /Users/a.cavalcanti/apps/servo/openssl/openssl-sys/src/old_openssl_shim.c -o /Users/a.cavalcanti/apps/servo/openssl/openssl/target/build/openssl-sys-8534a153cdebdd74/out/src/old_openssl_shim.o

I'm unfamiliar how cargo calls pkg-config while building something, but maybe it is being invoked with some missing environment flags? (e.g. PKG_CONFIG_PATH, etc).

I know rust-openssl doesn't officially supports OSX, but we use it in Servo (that supports OSX). I would  like to hear some feedback on what you think about the subject and what you feel would be the right fix?

Regards

Savago
* located at: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/hmac.

** located at:
/opt/local/include/openssl/hmac.h

*** flags:

a.cavalcanti ~/apps/servo/openssl/openssl $ cargo build
   Compiling openssl-sys v0.3.6 (file:///Users/a.cavalcanti/apps/servo/openssl/openssl)
failed to run custom build command for `openssl-sys v0.3.6 (file:///Users/a.cavalcanti/apps/servo/openssl/openssl)`
Process didn't exit successfully: `/Users/a.cavalcanti/apps/servo/openssl/openssl/target/build/openssl-sys-8534a153cdebdd74/build-script-build` (status=101)
--- stdout
cargo:rustc-flags=-L native=/opt/local/lib
cargo:rustc-flags=-l ssl
cargo:rustc-flags=-l crypto
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
CARGO_MANIFEST_DIR = Some("/Users/a.cavalcanti/apps/servo/openssl/openssl-sys")
OUT_DIR = Some("/Users/a.cavalcanti/apps/servo/openssl/openssl/target/build/openssl-sys-8534a153cdebdd74/out")
running: "cc" '"-O0"' '"-c"' '"-ffunction-sections"' '"-fdata-sections"' '"-m64"' '"-fPIC"' '"/Users/a.cavalcanti/apps/servo/openssl/openssl-sys/src/old_openssl_shim.c"' '"-o"' '"/Users/a.cavalcanti/apps/servo/openssl/openssl/target/build/openssl-sys-8534a153cdebdd74/out/src/old_openssl_shim.o"'

**Comment by sfackler** [comment]
Looks like it's due to the fact that pkg-config is finding the openssl copy in /opt but we're not passing the include directories to gcc so it's finding the default system version. This commit should fix it, could you try building with that? https://github.com/sfackler/rust-openssl/commit/d4c5bafa19d3142ca64d95bf0e531945da2db056

**Comment by Adenilson** [comment]
sfackler

I tried the new hash but build still fails. From an admittedly small sample (4 macbooks, that is including macs from people working on Servo) it seems that 1/2 will just build fine as rust-openssl is (even before the change to use the include dir information) and the other half will continue to fail *even* with the new change.

We can blame XCode and the broken state of package management in OSX (e.g. people use brew, BSD ports, etc).

Anyway, by luck I happen to have 2 macs available where one was able to build (OSX 10.9.5 i.e. Mavericks) while the other (OSX 10.10 i.e. Yosemite) was failing. By applying the patch I'm asking to be merged, build will work in both machines.

I tested this in Linux (Ubuntu 14.10) and doesn't cause any regression. Since the change will only affect OSX (i.e. darwin), I would say this is a quite safe patch and shouldn't affect any of the other supported OSes.

A question though: is there a reason not *always* pass the include path information to build_old_openssl_shim()?

Cheers

Adenilson

**Comment by sfackler** [comment]
Yeah, whoops, we should always just pass it through: 9cb3b44

**Comment by Adenilson** [comment]
There is what seems to be a logic error on master. You see, pkg-config will find openssl 1.0 and the code will just happily invoke build_old_openssl_shim() with no include path information.

Then gcc/clang will use the default system include path i.e. the one in Xcode.

**Comment by Adenilson** [comment]
Just confirming the master is fixed now.
